# Generated by Django 5.1.1 on 2025-02-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ai",
            name="body",
        ),
        migrations.RemoveField(
            model_name="ai",
            name="title",
        ),
        migrations.AddField(
            model_name="ai",
            name="answer",
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name="ai",
            name="question",
            field=models.TextField(default=None),
        ),
    ]
