# Generated by Django 5.1.1 on 2025-02-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0003_alter_ai_answer_alter_ai_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ai",
            name="answer",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ai",
            name="question",
            field=models.TextField(blank=True, null=True),
        ),
    ]
